name: EithonFixesPlugin
main: se.fredsfursten.eithonfixesplugin.EithonFixesPlugin
version: 0.3
author: vanbrayne
depend: [Essentials]
description: A Minecraft plugin for Eithon fixes
commands:
  eithonfixes:
    description: Fix things other plugins fail to do
    usage: /eithonfixes buy
    permission-message: You don't have <permission>
permissions:
  eithonfixes.*:
    description: Gives access to all eithonfixes commands
    default: op
    eithonfixes.buy: true
  eithonfixes.buy:
    description: Access to /eithonfixes buy command
    default: op
